# This file is part of GUFI, which is part of MarFS, which is released
# under the BSD license.
#
#
# Copyright (c) 2017, Los Alamos National Security (LANS), LLC
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation and/or
# other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
# may be used to endorse or promote products derived from this software without
# specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
# ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#
# From Los Alamos National Security, LLC:
# LA-CC-15-039
#
# Copyright (c) 2017, Los Alamos National Security, LLC All rights reserved.
# Copyright 2017. Los Alamos National Security, LLC. This software was produced
# under U.S. Government contract DE-AC52-06NA25396 for Los Alamos National
# Laboratory (LANL), which is operated by Los Alamos National Security, LLC for
# the U.S. Department of Energy. The U.S. Government has rights to use,
# reproduce, and distribute this software.  NEITHER THE GOVERNMENT NOR LOS
# ALAMOS NATIONAL SECURITY, LLC MAKES ANY WARRANTY, EXPRESS OR IMPLIED, OR
# ASSUMES ANY LIABILITY FOR THE USE OF THIS SOFTWARE.  If software is
# modified to produce derivative works, such modified software should be
# clearly marked, so as not to confuse it with the version available from
# LANL.
#
# THIS SOFTWARE IS PROVIDED BY LOS ALAMOS NATIONAL SECURITY, LLC AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL LOS ALAMOS NATIONAL SECURITY, LLC OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
# OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
# OF SUCH DAMAGE.



name: Install

on: [push, pull_request]

env:
  CC: clang
  CXX: clang++
  DEP_INSTALL_PREFIX: ~/.local
  COMMON_CONFIG: -DCMAKE_C_FLAGS="-Wall -Wextra -Werror -pedantic" -DCMAKE_CXX_FLAGS="-Wall -Wextra -Werror -pedantic" -DDEP_INSTALL_PREFIX="${DEP_INSTALL_PREFIX}" -DDEP_BUILD_THREADS=2
  PIP_BREAK_SYSTEM_PACKAGES: 1

jobs:
  RPMs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        client: [ Off, On ]
    container:
      image: rockylinux:9
    steps:
    - uses: actions/checkout@v4

    - uses: actions/cache@v4
      with:
        path: ${{ env.DEP_INSTALL_PREFIX }}
        key:  ${{ runner.os }}-Client-${{ matrix.client }}

    - name: Rocky Linux Prerequisites
      run:  contrib/CI/rockylinux.sh

    - name: Install Python Packages
      run:  python3 -m pip install -r contrib/CI/requirements.txt

    - name: Configure CMake
      run:  |
            mkdir build
            cd build
            cmake .. ${{ env.COMMON_CONFIG }} -DCLIENT="${{ matrix.client }}"

    - name: Test Generic RPM
      if:   matrix.client == 'Off'
      working-directory: build
      run:  contrib/CI/generic_rpm.sh

    - name: Test Server and Client RPMs
      if:   matrix.client == 'On'
      working-directory: build
      run:  contrib/CI/rpms.sh

    - name: Upload RPMs
      uses: softprops/action-gh-release@v2
      if:   startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ github.workspace }}/build/*.rpm

  Install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [ 'CMake', 'Make' ]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - uses: actions/cache@v4
      with:
        path: ${{ env.DEP_INSTALL_PREFIX }}
        key:  ${{ runner.os }}-${{ matrix.type }}-Install

    - name: Ubuntu Prerequisites
      run:  sudo contrib/CI/ubuntu.sh

    - name: Install Python Packages
      run:  python3 -m pip install -r contrib/CI/requirements.txt

    - name: Configure CMake
      run:  cmake -B ${{ github.workspace }}/build ${{ env.COMMON_CONFIG }}

    - name: Build
      run:  cmake --build ${{ github.workspace }}/build -j

    - name: CMake Install
      if:   matrix.type == 'CMake'
      run:  sudo cmake --install .
      working-directory: ${{ github.workspace }}/build

    - name: Make Install
      if:   matrix.type == 'Make'
      run:  sudo make install
      working-directory: ${{ github.workspace }}/build

    - name: Find Executables
      run:  |
        while IFS= read -r -d $'\0' name
        do
            which "${name}"
        done < <(find src scripts -maxdepth 1 \( -name "gufi_*" -a -not -name "*.*" \) -type f -executable -printf "%P\0" | sort -z)
      working-directory: ${{ github.workspace }}/build
